server:
  port: 8080

spring:
  profiles:
    active: dev
  security:
    user:
      name: fshuai
      password: fshuai
  jackson:
    date-format: yyyy-MM-dd
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  servlet:
    multipart:
      max-request-size: ${sky.servlet.multipart.max-request-size}
      max-file-size: ${sky.servlet.multipart.max-file-size}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      fshuai:
        mapper: debug
        service: info
        controller: info

fshuai:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    teacher-secret-key: fshuai1203
    # 设置jwt过期时间
    teacher-ttl: 7200000
    # 设置前端传递过来的令牌名称
    teacher-token-name: teacher-token
    teacher-id-key: teacherId
    teacher-role-key: teacherRole
    teacher-dept-key: teacherDept


    student-secret-key: fshuai
    student-ttl: 7200000
    student-token-name: student-token

document:
  uploadPath: ${document.uploadPath}


