csie:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: csie
    username: root
    password: fshuai1203
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tPQn7nMwADVTtkkEDbv
    accessKeySecret: en00507oc36uua85xyzKsA9S8LgZFM
    bucketName: csie
  redis:
    host: localhost
    port: 6379
    password: fshuai1203
    database: 0
  servlet:
    multipart:
      max-request-size: 300MB
      max-file-size: 30MB


document:
  uploadPath: /Users/fengshuai/Documents/project/java/spring/csie/data/images